# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gloader 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "gloader"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Benedict Dodd"]
  s.date = "2013-10-16"
  s.description = "Buids Grinder load test platform and controls test runs"
  s.email = "mail@bendodd.com"
  s.executables = ["gloader"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rbenv-gemsets",
    ".rubocop.yml",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/gloader",
    "gloader.gemspec",
    "lib/gloader.rb",
    "lib/gloader/chef.rb",
    "lib/gloader/cli.rb",
    "lib/gloader/config.rb",
    "lib/gloader/console.rb",
    "lib/gloader/core.rb",
    "lib/gloader/iaas.rb",
    "lib/gloader/iaas/aws.rb",
    "lib/gloader/iaas/rackspace.rb",
    "lib/gloader/logger.rb",
    "lib/gloader/platform.rb",
    "lib/gloader/test_run.rb",
    "lib/gloader/version.rb",
    "spec/integration/gloader/build_spec.rb",
    "spec/integration/gloader/cli_spec.rb",
    "spec/integration/gloader/test_run_spec.rb",
    "spec/integration/spec_helper.rb",
    "spec/specs_helper.rb",
    "spec/unit/fixtures/.gitignore",
    "spec/unit/fixtures/config_gloader_default.yml",
    "spec/unit/fixtures/config_gloader_state.yml",
    "spec/unit/gloader/chef_spec.rb",
    "spec/unit/gloader/cli_spec.rb",
    "spec/unit/gloader/config_spec.rb",
    "spec/unit/gloader/console_spec.rb",
    "spec/unit/gloader/core_spec.rb",
    "spec/unit/gloader/iaas/aws_spec.rb",
    "spec/unit/gloader/iaas/rackspace_spec.rb",
    "spec/unit/gloader/iaas_spec.rb",
    "spec/unit/gloader/logger_spec.rb",
    "spec/unit/gloader/platform_spec.rb",
    "spec/unit/gloader/test_run_spec.rb",
    "spec/unit/spec_helper.rb",
    "tools/GrinderAnalyzer/analyzer.py",
    "tools/GrinderAnalyzer/classpathtool.py",
    "tools/GrinderAnalyzer/conf/analyzer.properties",
    "tools/GrinderAnalyzer/extra/README.txt",
    "tools/GrinderAnalyzer/extra/glf/.project",
    "tools/GrinderAnalyzer/extra/glf/.pydevproject",
    "tools/GrinderAnalyzer/extra/glf/README.txt",
    "tools/GrinderAnalyzer/extra/glf/release.sh",
    "tools/GrinderAnalyzer/extra/glf/src/feeder/__init__.py",
    "tools/GrinderAnalyzer/extra/glf/src/feeder/aggregator.py",
    "tools/GrinderAnalyzer/extra/glf/src/feeder/fileutils.py",
    "tools/GrinderAnalyzer/extra/glf/src/feeder/line.py",
    "tools/GrinderAnalyzer/extra/glf/src/foo.py",
    "tools/GrinderAnalyzer/extra/glf/src/graphite_log_feeder.py",
    "tools/GrinderAnalyzer/extra/glf/src/settings.py",
    "tools/GrinderAnalyzer/extra/logster/GrinderLogster.py",
    "tools/GrinderAnalyzer/ga/__init__.py",
    "tools/GrinderAnalyzer/ga/bucket.py",
    "tools/GrinderAnalyzer/ga/constants.py",
    "tools/GrinderAnalyzer/ga/fileutils.py",
    "tools/GrinderAnalyzer/ga/graph.py",
    "tools/GrinderAnalyzer/ga/report.py",
    "tools/GrinderAnalyzer/ga/summary.py",
    "tools/GrinderAnalyzer/lib/GrinderAnalyzer.V2.b19.jar",
    "tools/GrinderAnalyzer/lib/commons-collections-3.2.jar",
    "tools/GrinderAnalyzer/lib/commons-lang-2.3.jar",
    "tools/GrinderAnalyzer/lib/htmllexer.jar",
    "tools/GrinderAnalyzer/lib/htmlparser.jar",
    "tools/GrinderAnalyzer/lib/jcommon-1.0.12.jar",
    "tools/GrinderAnalyzer/lib/jfreechart-1.0.9.jar",
    "tools/GrinderAnalyzer/lib/log4j.jar",
    "tools/GrinderAnalyzer/lib/velocity-1.5.jar",
    "tools/GrinderAnalyzer/templates/agent.vm",
    "tools/GrinderAnalyzer/templates/analyzer.css",
    "tools/GrinderAnalyzer/templates/csshover3.htc",
    "tools/GrinderAnalyzer/templates/sorttable.js",
    "tools/GrinderAnalyzer/templates/wz_tooltip.js",
    "tools/chef/cookbooks/apt/CHANGELOG.md",
    "tools/chef/cookbooks/apt/CONTRIBUTING",
    "tools/chef/cookbooks/apt/LICENSE",
    "tools/chef/cookbooks/apt/README.md",
    "tools/chef/cookbooks/apt/files/default/apt-proxy-v2.conf",
    "tools/chef/cookbooks/apt/metadata.json",
    "tools/chef/cookbooks/apt/metadata.rb",
    "tools/chef/cookbooks/apt/providers/preference.rb",
    "tools/chef/cookbooks/apt/providers/repository.rb",
    "tools/chef/cookbooks/apt/recipes/cacher-client.rb",
    "tools/chef/cookbooks/apt/recipes/cacher-ng.rb",
    "tools/chef/cookbooks/apt/recipes/default.rb",
    "tools/chef/cookbooks/apt/resources/preference.rb",
    "tools/chef/cookbooks/apt/resources/repository.rb",
    "tools/chef/cookbooks/ark/.gitignore",
    "tools/chef/cookbooks/ark/.travis.yml",
    "tools/chef/cookbooks/ark/CHANGELOG.md",
    "tools/chef/cookbooks/ark/README.md",
    "tools/chef/cookbooks/ark/Rakefile",
    "tools/chef/cookbooks/ark/Toftfile",
    "tools/chef/cookbooks/ark/Vagrantfile",
    "tools/chef/cookbooks/ark/attributes/default.rb",
    "tools/chef/cookbooks/ark/files/default/foo.tar.gz",
    "tools/chef/cookbooks/ark/files/default/foo.tbz",
    "tools/chef/cookbooks/ark/files/default/foo.tgz",
    "tools/chef/cookbooks/ark/files/default/foo.zip",
    "tools/chef/cookbooks/ark/files/default/tests/minitest/test_test.rb",
    "tools/chef/cookbooks/ark/libraries/provider_ark.rb",
    "tools/chef/cookbooks/ark/libraries/resource_ark.rb",
    "tools/chef/cookbooks/ark/metadata.json",
    "tools/chef/cookbooks/ark/metadata.rb",
    "tools/chef/cookbooks/ark/recipes/default.rb",
    "tools/chef/cookbooks/ark/recipes/test.rb",
    "tools/chef/cookbooks/build-essential/CHANGELOG.md",
    "tools/chef/cookbooks/build-essential/CONTRIBUTING",
    "tools/chef/cookbooks/build-essential/LICENSE",
    "tools/chef/cookbooks/build-essential/README.md",
    "tools/chef/cookbooks/build-essential/attributes/default.rb",
    "tools/chef/cookbooks/build-essential/metadata.json",
    "tools/chef/cookbooks/build-essential/metadata.rb",
    "tools/chef/cookbooks/build-essential/recipes/default.rb",
    "tools/chef/cookbooks/bundler/attributes/bundler.rb",
    "tools/chef/cookbooks/bundler/metadata.json",
    "tools/chef/cookbooks/bundler/readme.md",
    "tools/chef/cookbooks/bundler/recipes/default.rb",
    "tools/chef/cookbooks/bundler/recipes/install.rb",
    "tools/chef/cookbooks/bundler/recipes/lock.rb",
    "tools/chef/cookbooks/bundler/recipes/pack.rb",
    "tools/chef/cookbooks/bundler/recipes/unlock.rb",
    "tools/chef/cookbooks/git/CHANGELOG.md",
    "tools/chef/cookbooks/git/CONTRIBUTING",
    "tools/chef/cookbooks/git/LICENSE",
    "tools/chef/cookbooks/git/README.md",
    "tools/chef/cookbooks/git/attributes/default.rb",
    "tools/chef/cookbooks/git/metadata.json",
    "tools/chef/cookbooks/git/metadata.rb",
    "tools/chef/cookbooks/git/recipes/default.rb",
    "tools/chef/cookbooks/git/recipes/server.rb",
    "tools/chef/cookbooks/git/templates/default/sv-git-daemon-log-run.erb",
    "tools/chef/cookbooks/git/templates/default/sv-git-daemon-run.erb",
    "tools/chef/cookbooks/grinder/README.md",
    "tools/chef/cookbooks/grinder/attributes/default.rb",
    "tools/chef/cookbooks/grinder/metadata.json",
    "tools/chef/cookbooks/grinder/metadata.rb",
    "tools/chef/cookbooks/grinder/recipes/default.rb",
    "tools/chef/cookbooks/java/CHANGELOG.md",
    "tools/chef/cookbooks/java/CONTRIBUTING",
    "tools/chef/cookbooks/java/LICENSE",
    "tools/chef/cookbooks/java/README.md",
    "tools/chef/cookbooks/java/attributes/default.rb",
    "tools/chef/cookbooks/java/metadata.json",
    "tools/chef/cookbooks/java/metadata.rb",
    "tools/chef/cookbooks/java/providers/ark.rb",
    "tools/chef/cookbooks/java/recipes/default.rb",
    "tools/chef/cookbooks/java/recipes/openjdk.rb",
    "tools/chef/cookbooks/java/recipes/oracle.rb",
    "tools/chef/cookbooks/java/recipes/oracle_i386.rb",
    "tools/chef/cookbooks/java/resources/ark.rb",
    "tools/chef/cookbooks/python/CHANGELOG.md",
    "tools/chef/cookbooks/python/CONTRIBUTING",
    "tools/chef/cookbooks/python/LICENSE",
    "tools/chef/cookbooks/python/README.md",
    "tools/chef/cookbooks/python/attributes/default.rb",
    "tools/chef/cookbooks/python/metadata.json",
    "tools/chef/cookbooks/python/metadata.rb",
    "tools/chef/cookbooks/python/providers/pip.rb",
    "tools/chef/cookbooks/python/providers/virtualenv.rb",
    "tools/chef/cookbooks/python/recipes/default.rb",
    "tools/chef/cookbooks/python/recipes/package.rb",
    "tools/chef/cookbooks/python/recipes/pip.rb",
    "tools/chef/cookbooks/python/recipes/source.rb",
    "tools/chef/cookbooks/python/recipes/virtualenv.rb",
    "tools/chef/cookbooks/python/resources/pip.rb",
    "tools/chef/cookbooks/python/resources/virtualenv.rb",
    "tools/chef/cookbooks/rbenv/.gitignore",
    "tools/chef/cookbooks/rbenv/.travis.yml",
    "tools/chef/cookbooks/rbenv/CHANGELOG.md",
    "tools/chef/cookbooks/rbenv/README.md",
    "tools/chef/cookbooks/rbenv/Rakefile",
    "tools/chef/cookbooks/rbenv/attributes/default.rb",
    "tools/chef/cookbooks/rbenv/libraries/chef_provider_package_rbenvrubygems.rb",
    "tools/chef/cookbooks/rbenv/libraries/chef_rbenv_mixin.rb",
    "tools/chef/cookbooks/rbenv/libraries/chef_rbenv_recipe_helpers.rb",
    "tools/chef/cookbooks/rbenv/libraries/chef_rbenv_script_helpers.rb",
    "tools/chef/cookbooks/rbenv/metadata.json",
    "tools/chef/cookbooks/rbenv/metadata.rb",
    "tools/chef/cookbooks/rbenv/providers/global.rb",
    "tools/chef/cookbooks/rbenv/providers/rehash.rb",
    "tools/chef/cookbooks/rbenv/providers/ruby.rb",
    "tools/chef/cookbooks/rbenv/providers/script.rb",
    "tools/chef/cookbooks/rbenv/recipes/default.rb",
    "tools/chef/cookbooks/rbenv/recipes/system.rb",
    "tools/chef/cookbooks/rbenv/recipes/system_install.rb",
    "tools/chef/cookbooks/rbenv/recipes/user.rb",
    "tools/chef/cookbooks/rbenv/recipes/user_install.rb",
    "tools/chef/cookbooks/rbenv/recipes/vagrant.rb",
    "tools/chef/cookbooks/rbenv/resources/gem.rb",
    "tools/chef/cookbooks/rbenv/resources/global.rb",
    "tools/chef/cookbooks/rbenv/resources/rehash.rb",
    "tools/chef/cookbooks/rbenv/resources/ruby.rb",
    "tools/chef/cookbooks/rbenv/resources/script.rb",
    "tools/chef/cookbooks/rbenv/templates/default/rbenv.sh.erb",
    "tools/chef/cookbooks/rbenv/test/support/Gemfile",
    "tools/chef/cookbooks/ruby_build/.gitignore",
    "tools/chef/cookbooks/ruby_build/.travis.yml",
    "tools/chef/cookbooks/ruby_build/CHANGELOG.md",
    "tools/chef/cookbooks/ruby_build/README.md",
    "tools/chef/cookbooks/ruby_build/Rakefile",
    "tools/chef/cookbooks/ruby_build/attributes/default.rb",
    "tools/chef/cookbooks/ruby_build/libraries/ruby_build_recipe_helpers.rb",
    "tools/chef/cookbooks/ruby_build/metadata.json",
    "tools/chef/cookbooks/ruby_build/metadata.rb",
    "tools/chef/cookbooks/ruby_build/providers/ruby.rb",
    "tools/chef/cookbooks/ruby_build/recipes/default.rb",
    "tools/chef/cookbooks/ruby_build/resources/ruby.rb",
    "tools/chef/cookbooks/runit/CHANGELOG.md",
    "tools/chef/cookbooks/runit/CONTRIBUTING",
    "tools/chef/cookbooks/runit/LICENSE",
    "tools/chef/cookbooks/runit/README.md",
    "tools/chef/cookbooks/runit/attributes/default.rb",
    "tools/chef/cookbooks/runit/definitions/runit_service.rb",
    "tools/chef/cookbooks/runit/files/default/runit.seed",
    "tools/chef/cookbooks/runit/files/default/runsvdir",
    "tools/chef/cookbooks/runit/files/ubuntu-6.10/runsvdir",
    "tools/chef/cookbooks/runit/files/ubuntu-7.04/runsvdir",
    "tools/chef/cookbooks/runit/files/ubuntu-7.10/runsvdir",
    "tools/chef/cookbooks/runit/files/ubuntu-8.04/runsvdir",
    "tools/chef/cookbooks/runit/metadata.json",
    "tools/chef/cookbooks/runit/metadata.rb",
    "tools/chef/cookbooks/runit/recipes/default.rb",
    "tools/chef/cookbooks/runit/templates/gentoo/runit-start.sh.erb",
    "tools/chef/cookbooks/sudo/README.md",
    "tools/chef/cookbooks/sudo/attributes/default.rb",
    "tools/chef/cookbooks/sudo/files/default/README.sudoers",
    "tools/chef/cookbooks/sudo/metadata.json",
    "tools/chef/cookbooks/sudo/metadata.rb",
    "tools/chef/cookbooks/sudo/providers/default.rb",
    "tools/chef/cookbooks/sudo/recipes/default.rb",
    "tools/chef/cookbooks/sudo/resources/default.rb",
    "tools/chef/cookbooks/sudo/templates/default/sudoers.erb",
    "tools/chef/data_bags/README",
    "tools/chef/nodes/README",
    "tools/chef/roles/README.md",
    "tools/chef/roles/load_test_agent.json",
    "tools/chef/roles/load_test_console.json",
    "tools/chef/site-cookbooks/README"
  ]
  s.homepage = "http://github.com/bendodd/gloader"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.9"
  s.summary = "Grinder Load Tester"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fog>, ["~> 1.16.0"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.12.0"])
      s.add_runtime_dependency(%q<json>, ["~> 1.8.0"])
      s.add_runtime_dependency(%q<sshkey>, ["~> 1.6.0"])
      s.add_runtime_dependency(%q<net-ssh>, ["~> 2.7.0"])
      s.add_runtime_dependency(%q<thor>, ["~> 0.18.1"])
      s.add_runtime_dependency(%q<log4r>, ["~> 1.1.10"])
      s.add_runtime_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_runtime_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_runtime_dependency(%q<slowweb>, ["~> 0.1.1"])
      s.add_runtime_dependency(%q<formatador>, ["~> 0.2.4"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rake>, [">= 0"])
      s.add_development_dependency(%q<guard-rubocop>, [">= 0"])
      s.add_development_dependency(%q<guard-bundler>, [">= 0"])
      s.add_development_dependency(%q<growl>, ["~> 1.0.3"])
      s.add_development_dependency(%q<rb-inotify>, ["~> 0.9"])
      s.add_development_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<fog>, ["~> 1.16.0"])
      s.add_dependency(%q<httparty>, ["~> 0.12.0"])
      s.add_dependency(%q<json>, ["~> 1.8.0"])
      s.add_dependency(%q<sshkey>, ["~> 1.6.0"])
      s.add_dependency(%q<net-ssh>, ["~> 2.7.0"])
      s.add_dependency(%q<thor>, ["~> 0.18.1"])
      s.add_dependency(%q<log4r>, ["~> 1.1.10"])
      s.add_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<slowweb>, ["~> 0.1.1"])
      s.add_dependency(%q<formatador>, ["~> 0.2.4"])
      s.add_dependency(%q<activesupport>, ["~> 3.2"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rake>, [">= 0"])
      s.add_dependency(%q<guard-rubocop>, [">= 0"])
      s.add_dependency(%q<guard-bundler>, [">= 0"])
      s.add_dependency(%q<growl>, ["~> 1.0.3"])
      s.add_dependency(%q<rb-inotify>, ["~> 0.9"])
      s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<fog>, ["~> 1.16.0"])
    s.add_dependency(%q<httparty>, ["~> 0.12.0"])
    s.add_dependency(%q<json>, ["~> 1.8.0"])
    s.add_dependency(%q<sshkey>, ["~> 1.6.0"])
    s.add_dependency(%q<net-ssh>, ["~> 2.7.0"])
    s.add_dependency(%q<thor>, ["~> 0.18.1"])
    s.add_dependency(%q<log4r>, ["~> 1.1.10"])
    s.add_dependency(%q<bundler>, ["~> 1.3.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<slowweb>, ["~> 0.1.1"])
    s.add_dependency(%q<formatador>, ["~> 0.2.4"])
    s.add_dependency(%q<activesupport>, ["~> 3.2"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rake>, [">= 0"])
    s.add_dependency(%q<guard-rubocop>, [">= 0"])
    s.add_dependency(%q<guard-bundler>, [">= 0"])
    s.add_dependency(%q<growl>, ["~> 1.0.3"])
    s.add_dependency(%q<rb-inotify>, ["~> 0.9"])
    s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

