
# Copyright (C) 2011-2012, Travis Bear
# All rights reserved.
#
# This file is part of Graphite Log Feeder.
#
# Graphite Log Feeder is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Graphite Log Feeder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Graphite Log Feeder; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA


######################################################################
# Graphite settings
######################################################################
carbon_interval_seconds = 10.0
carbon_host = "qa-perf005"
carbon_port = 2003

# no trailing '.'  simple host name will be appended to this value
# to generate the full path into the carbon data tree.  The default
# value should be fine in most cases.
carbon_prefix = "servers" 



######################################################################
# Data settings
######################################################################

# Grinder Line Reader is currently the only implementation available.
# Apache, Scribe, and other line readers can easily be added. 
line_reader = "line.GrinderLineReader"

# report on the timer statistics that fall in these different
# groups.  Set to empty list to disable.
#
# time_group_milliseconds = [] # disables time grouping feature
time_group_milliseconds = [20, 50]



######################################################################
# Grinder settings
#
# Settings in this section only apply if a grinder log reader is
# selected.  These defaults can be overridden with command line
# options.
######################################################################

# This will be your data_* file generated by the Grinder Agent.
#default_data_file = "/usr/local/grinder/logs/data_ubuntu-0.log"
default_data_file = "/home/travis/data_ubuntu-0.log"

# This will be the grinder out_* file from the Grinder run.  It is
# possible (but not recommended) to use an out_* file from a
# different run, provided it uses the exact same transaction
# numbers.
#default_mapping_file = "/usr/local/grinder/logs/out_ubuntu-0.log"
default_mapping_file = "/home/travis/out_ubuntu-0.log"
